@echo off
echo FocusFlow Mobile MVP Baslatiliyor...
echo Bağımlılıklar kontrol ediliyor (npm install)...
call npm install
echo.
echo Metro Bundler Baslatiliyor (expo start)...
call npx expo start
pause
