spring:
  application:
    name: focusFlow
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/focusFlow
    username: postgres
    password: "12345"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  h2:
    console:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/focusFlow}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

---
# Ortak Ayarlar
jwt:
  secret: ${JWT_SECRET:your-super-secret-key-change-in-production}
  expiration: 86400000

server:
  port: 8080

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.tezprojesi: DEBUG
